# -----------------------------------------------------------------------------
# AndroidWorld Benchmark Configuration V2 - Windows 11
#
# This file centralizes all settings for running benchmarks and tasks on Windows.
# It is designed to be modular, with specific settings for each agent.
# -----------------------------------------------------------------------------

# =============================================================================
# SCRIPT BEHAVIOR
# =============================================================================
script:
  activate_conda: true
  conda_env_name: "android_world"
  start_emulator: true
  
  # Controls the one-time emulator setup (app installation).
  # - "run_once": (Default) The script will run setup if a marker file 
  #   (.emulator_setup_completed) is not found. If it is found, it will skip.
  # - "force_run": Will run setup regardless of whether it was run before.
  # - "skip": Will always skip setup.
  perform_emulator_setup: "skip"


# =============================================================================
# RUN CONFIGURATION
# =============================================================================
run:
  # "fast" for a single test run, "full" for the complete benchmark suite.
  mode: "fast"
  verbose: true


# =============================================================================
# AGENT CONFIGURATION
# =============================================================================
agent:
  # Specifies which agent configuration to use from the `configurations` block below.
  active_agent: "m3a_gemini"

  # --- Agent-Specific Settings ---
  # Each agent has its own configuration block. The script will only use the
  # settings for the `active_agent` specified above.
  configurations:
    
    # Configuration for the M3A OpenRouter agent
    m3a_openrouter:
      # This name must match the agent's name in the registry.
      registry_name: "m3a_openrouter_agent"
      
      # The specific LLM model to use via OpenRouter.
      # See https://openrouter.ai/models for a full list.
      model_name: "google/gemma-3-27b-it:free"
      
      # LLM generation temperature.
      temperature: 0.0
      
      # Max number of retries for API calls.
      max_retry: 3
      
      # Seconds to wait for UI to stabilize after an action.
      wait_after_action_seconds: 2.0
      

    # Configuration for the M3A Gemini Gemma agent
    m3a_gemini:
      # This name must match the agent's name in the registry.
      registry_name: "m3a_gemini_gemma_agent"
      
      # The specific Gemma model to use via the Gemini API.
      model_name: "gemma-3-27b-it"

      # LLM generation temperature.
      temperature: 0.0
      
      # Top-p sampling parameter for the Gemini API.
      top_p: 0.95
      
      # Max number of retries for API calls.
      max_retry: 3
      
      # Seconds to wait for UI to stabilize after an action.
      wait_after_action_seconds: 2.0
      
      # Whether to enable the built-in Gemini safety checks.
      enable_safety_checks: true


# =============================================================================
# TASK CONFIGURATION
# =============================================================================
task:
  # Specific task to run. If null, a random/full suite is used.
  # Example: "ContactsAddContact"
  name: null
  suite_family: "android_world"
  n_task_combinations: 1 # For "full" mode
  random_seed: 30


# =============================================================================
# ENVIRONMENT CONFIGURATION
# =============================================================================
environment:
  console_port: 5554
  emulator_log_path: "emulator.log"
  
  # Path to the Android SDK root directory for Windows.
  # Common Windows locations are:
  # - %LOCALAPPDATA%\Android\Sdk (most common for personal installs)
  # - %USERPROFILE%\AppData\Local\Android\Sdk (alternative location)
  # - C:\Program Files (x86)\Android\android-sdk (system-wide install)
  # The script will expand environment variables automatically.
  android_sdk_root: "%LOCALAPPDATA%\\Android\\Sdk" 